# Generated by Django 3.1 on 2020-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_youtubecontent_you_conlikesuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='Rec_conName',
            field=models.CharField(help_text='제목', max_length=50, verbose_name='TITLE'),
        ),
    ]
